#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="admin_HShop")]
public partial class LinqDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAdmin(Admin instance);
  partial void UpdateAdmin(Admin instance);
  partial void DeleteAdmin(Admin instance);
  partial void InsertUser(User instance);
  partial void UpdateUser(User instance);
  partial void DeleteUser(User instance);
  partial void InsertCategory(Category instance);
  partial void UpdateCategory(Category instance);
  partial void DeleteCategory(Category instance);
  partial void InsertDonHang(DonHang instance);
  partial void UpdateDonHang(DonHang instance);
  partial void DeleteDonHang(DonHang instance);
  partial void InsertMatHang(MatHang instance);
  partial void UpdateMatHang(MatHang instance);
  partial void DeleteMatHang(MatHang instance);
  partial void InsertSetting(Setting instance);
  partial void UpdateSetting(Setting instance);
  partial void DeleteSetting(Setting instance);
  partial void InserttblEmailTemplate(tblEmailTemplate instance);
  partial void UpdatetblEmailTemplate(tblEmailTemplate instance);
  partial void DeletetblEmailTemplate(tblEmailTemplate instance);
  partial void InsertTinTuc(TinTuc instance);
  partial void UpdateTinTuc(TinTuc instance);
  partial void DeleteTinTuc(TinTuc instance);
  #endregion
	
	public LinqDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Connection"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Admin> Admins
	{
		get
		{
			return this.GetTable<Admin>();
		}
	}
	
	public System.Data.Linq.Table<User> Users
	{
		get
		{
			return this.GetTable<User>();
		}
	}
	
	public System.Data.Linq.Table<Category> Categories
	{
		get
		{
			return this.GetTable<Category>();
		}
	}
	
	public System.Data.Linq.Table<DonHang> DonHangs
	{
		get
		{
			return this.GetTable<DonHang>();
		}
	}
	
	public System.Data.Linq.Table<ip2location_db1> ip2location_db1s
	{
		get
		{
			return this.GetTable<ip2location_db1>();
		}
	}
	
	public System.Data.Linq.Table<MatHang> MatHangs
	{
		get
		{
			return this.GetTable<MatHang>();
		}
	}
	
	public System.Data.Linq.Table<Setting> Settings
	{
		get
		{
			return this.GetTable<Setting>();
		}
	}
	
	public System.Data.Linq.Table<tblEmailTemplate> tblEmailTemplates
	{
		get
		{
			return this.GetTable<tblEmailTemplate>();
		}
	}
	
	public System.Data.Linq.Table<TinTuc> TinTucs
	{
		get
		{
			return this.GetTable<TinTuc>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sosanhstring", IsComposable=true)]
	public System.Nullable<bool> sosanhstring([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string txt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string txt2)
	{
		return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), txt, txt2).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ischuyengiainchuyenganh", IsComposable=true)]
	public System.Nullable<int> ischuyengiainchuyenganh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string txt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string txt2)
	{
		return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), txt, txt2).ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.returnDateTime", IsComposable=true)]
	public System.Nullable<System.DateTime> returnDateTime([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date2)
	{
		return ((System.Nullable<System.DateTime>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date, date2).ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ID;
	
	private string _UserName;
	
	private string _Password;
	
	private string _Email;
	
	private string _FullName;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
	
	public Admin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(128)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(128)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(128)")]
	public string FullName
	{
		get
		{
			return this._FullName;
		}
		set
		{
			if ((this._FullName != value))
			{
				this.OnFullNameChanging(value);
				this.SendPropertyChanging();
				this._FullName = value;
				this.SendPropertyChanged("FullName");
				this.OnFullNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ID;
	
	private string _Email;
	
	private string _FullName;
	
	private string _Password;
	
	private System.Nullable<System.DateTime> _CreateDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    #endregion
	
	public User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(500)")]
	public string FullName
	{
		get
		{
			return this._FullName;
		}
		set
		{
			if ((this._FullName != value))
			{
				this.OnFullNameChanging(value);
				this.SendPropertyChanging();
				this._FullName = value;
				this.SendPropertyChanged("FullName");
				this.OnFullNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(500)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ID;
	
	private string _Name;
	
	private string _ParentID;
	
	private string _Img;
	
	private System.DateTime _CreateDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnParentIDChanging(string value);
    partial void OnParentIDChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
	
	public Category()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
	public string ParentID
	{
		get
		{
			return this._ParentID;
		}
		set
		{
			if ((this._ParentID != value))
			{
				this.OnParentIDChanging(value);
				this.SendPropertyChanging();
				this._ParentID = value;
				this.SendPropertyChanged("ParentID");
				this.OnParentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Img
	{
		get
		{
			return this._Img;
		}
		set
		{
			if ((this._Img != value))
			{
				this.OnImgChanging(value);
				this.SendPropertyChanging();
				this._Img = value;
				this.SendPropertyChanged("Img");
				this.OnImgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
	public System.DateTime CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonHang")]
public partial class DonHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ID;
	
	private string _UserID;
	
	private string _ID_Related_Resources;
	
	private string _PayerID;
	
	private string _Payer_Info;
	
	private string _PaymentId;
	
	private string _Shipping_Address;
	
	private decimal _TotalMoney;
	
	private decimal _TotalShipping;
	
	private decimal _TotalTax;
	
	private int _TotalItems;
	
	private string _DetailItems;
	
	private int _Status;
	
	private System.DateTime _CreateDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnID_Related_ResourcesChanging(string value);
    partial void OnID_Related_ResourcesChanged();
    partial void OnPayerIDChanging(string value);
    partial void OnPayerIDChanged();
    partial void OnPayer_InfoChanging(string value);
    partial void OnPayer_InfoChanged();
    partial void OnPaymentIdChanging(string value);
    partial void OnPaymentIdChanged();
    partial void OnShipping_AddressChanging(string value);
    partial void OnShipping_AddressChanged();
    partial void OnTotalMoneyChanging(decimal value);
    partial void OnTotalMoneyChanged();
    partial void OnTotalShippingChanging(decimal value);
    partial void OnTotalShippingChanged();
    partial void OnTotalTaxChanging(decimal value);
    partial void OnTotalTaxChanged();
    partial void OnTotalItemsChanging(int value);
    partial void OnTotalItemsChanged();
    partial void OnDetailItemsChanging(string value);
    partial void OnDetailItemsChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
	
	public DonHang()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Related_Resources", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
	public string ID_Related_Resources
	{
		get
		{
			return this._ID_Related_Resources;
		}
		set
		{
			if ((this._ID_Related_Resources != value))
			{
				this.OnID_Related_ResourcesChanging(value);
				this.SendPropertyChanging();
				this._ID_Related_Resources = value;
				this.SendPropertyChanged("ID_Related_Resources");
				this.OnID_Related_ResourcesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayerID", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
	public string PayerID
	{
		get
		{
			return this._PayerID;
		}
		set
		{
			if ((this._PayerID != value))
			{
				this.OnPayerIDChanging(value);
				this.SendPropertyChanging();
				this._PayerID = value;
				this.SendPropertyChanged("PayerID");
				this.OnPayerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payer_Info", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Payer_Info
	{
		get
		{
			return this._Payer_Info;
		}
		set
		{
			if ((this._Payer_Info != value))
			{
				this.OnPayer_InfoChanging(value);
				this.SendPropertyChanging();
				this._Payer_Info = value;
				this.SendPropertyChanged("Payer_Info");
				this.OnPayer_InfoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentId", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string PaymentId
	{
		get
		{
			return this._PaymentId;
		}
		set
		{
			if ((this._PaymentId != value))
			{
				this.OnPaymentIdChanging(value);
				this.SendPropertyChanging();
				this._PaymentId = value;
				this.SendPropertyChanged("PaymentId");
				this.OnPaymentIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shipping_Address", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Shipping_Address
	{
		get
		{
			return this._Shipping_Address;
		}
		set
		{
			if ((this._Shipping_Address != value))
			{
				this.OnShipping_AddressChanging(value);
				this.SendPropertyChanging();
				this._Shipping_Address = value;
				this.SendPropertyChanged("Shipping_Address");
				this.OnShipping_AddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalMoney", DbType="Decimal(18,2) NOT NULL")]
	public decimal TotalMoney
	{
		get
		{
			return this._TotalMoney;
		}
		set
		{
			if ((this._TotalMoney != value))
			{
				this.OnTotalMoneyChanging(value);
				this.SendPropertyChanging();
				this._TotalMoney = value;
				this.SendPropertyChanged("TotalMoney");
				this.OnTotalMoneyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalShipping", DbType="Decimal(18,2) NOT NULL")]
	public decimal TotalShipping
	{
		get
		{
			return this._TotalShipping;
		}
		set
		{
			if ((this._TotalShipping != value))
			{
				this.OnTotalShippingChanging(value);
				this.SendPropertyChanging();
				this._TotalShipping = value;
				this.SendPropertyChanged("TotalShipping");
				this.OnTotalShippingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalTax", DbType="Decimal(18,2) NOT NULL")]
	public decimal TotalTax
	{
		get
		{
			return this._TotalTax;
		}
		set
		{
			if ((this._TotalTax != value))
			{
				this.OnTotalTaxChanging(value);
				this.SendPropertyChanging();
				this._TotalTax = value;
				this.SendPropertyChanged("TotalTax");
				this.OnTotalTaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalItems", DbType="Int NOT NULL")]
	public int TotalItems
	{
		get
		{
			return this._TotalItems;
		}
		set
		{
			if ((this._TotalItems != value))
			{
				this.OnTotalItemsChanging(value);
				this.SendPropertyChanging();
				this._TotalItems = value;
				this.SendPropertyChanged("TotalItems");
				this.OnTotalItemsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailItems", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string DetailItems
	{
		get
		{
			return this._DetailItems;
		}
		set
		{
			if ((this._DetailItems != value))
			{
				this.OnDetailItemsChanging(value);
				this.SendPropertyChanging();
				this._DetailItems = value;
				this.SendPropertyChanged("DetailItems");
				this.OnDetailItemsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
	public int Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
	public System.DateTime CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ip2location_db1")]
public partial class ip2location_db1
{
	
	private double _ip_from;
	
	private double _ip_to;
	
	private string _country_code;
	
	private string _country_name;
	
	public ip2location_db1()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_from", DbType="Float NOT NULL")]
	public double ip_from
	{
		get
		{
			return this._ip_from;
		}
		set
		{
			if ((this._ip_from != value))
			{
				this._ip_from = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ip_to", DbType="Float NOT NULL")]
	public double ip_to
	{
		get
		{
			return this._ip_to;
		}
		set
		{
			if ((this._ip_to != value))
			{
				this._ip_to = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_code", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
	public string country_code
	{
		get
		{
			return this._country_code;
		}
		set
		{
			if ((this._country_code != value))
			{
				this._country_code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_name", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
	public string country_name
	{
		get
		{
			return this._country_name;
		}
		set
		{
			if ((this._country_name != value))
			{
				this._country_name = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MatHang")]
public partial class MatHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ID;
	
	private string _ParentID;
	
	private string _MaSP;
	
	private string _Title;
	
	private string _Img;
	
	private string _NoiBat;
	
	private string _ChiTiet;
	
	private string _Category;
	
	private System.Nullable<int> _GiaBan;
	
	private System.Nullable<int> _SoLuong;
	
	private System.Nullable<bool> _isHot;
	
	private string _ColorAndSize;
	
	private System.Nullable<int> _GiamGia;
	
	private int _Status;
	
	private System.DateTime _CreateDate;
	
	private EntitySet<MatHang> _MatHangs;
	
	private EntityRef<MatHang> _MatHang1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnParentIDChanging(string value);
    partial void OnParentIDChanged();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    partial void OnNoiBatChanging(string value);
    partial void OnNoiBatChanged();
    partial void OnChiTietChanging(string value);
    partial void OnChiTietChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnGiaBanChanging(System.Nullable<int> value);
    partial void OnGiaBanChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnisHotChanging(System.Nullable<bool> value);
    partial void OnisHotChanged();
    partial void OnColorAndSizeChanging(string value);
    partial void OnColorAndSizeChanged();
    partial void OnGiamGiaChanging(System.Nullable<int> value);
    partial void OnGiamGiaChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
	
	public MatHang()
	{
		this._MatHangs = new EntitySet<MatHang>(new Action<MatHang>(this.attach_MatHangs), new Action<MatHang>(this.detach_MatHangs));
		this._MatHang1 = default(EntityRef<MatHang>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="NVarChar(128)")]
	public string ParentID
	{
		get
		{
			return this._ParentID;
		}
		set
		{
			if ((this._ParentID != value))
			{
				if (this._MatHang1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnParentIDChanging(value);
				this.SendPropertyChanging();
				this._ParentID = value;
				this.SendPropertyChanged("ParentID");
				this.OnParentIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(100)")]
	public string MaSP
	{
		get
		{
			return this._MaSP;
		}
		set
		{
			if ((this._MaSP != value))
			{
				this.OnMaSPChanging(value);
				this.SendPropertyChanging();
				this._MaSP = value;
				this.SendPropertyChanged("MaSP");
				this.OnMaSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="NVarChar(MAX)")]
	public string Img
	{
		get
		{
			return this._Img;
		}
		set
		{
			if ((this._Img != value))
			{
				this.OnImgChanging(value);
				this.SendPropertyChanging();
				this._Img = value;
				this.SendPropertyChanged("Img");
				this.OnImgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiBat", DbType="NVarChar(MAX)")]
	public string NoiBat
	{
		get
		{
			return this._NoiBat;
		}
		set
		{
			if ((this._NoiBat != value))
			{
				this.OnNoiBatChanging(value);
				this.SendPropertyChanging();
				this._NoiBat = value;
				this.SendPropertyChanged("NoiBat");
				this.OnNoiBatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiTiet", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string ChiTiet
	{
		get
		{
			return this._ChiTiet;
		}
		set
		{
			if ((this._ChiTiet != value))
			{
				this.OnChiTietChanging(value);
				this.SendPropertyChanging();
				this._ChiTiet = value;
				this.SendPropertyChanged("ChiTiet");
				this.OnChiTietChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(MAX)")]
	public string Category
	{
		get
		{
			return this._Category;
		}
		set
		{
			if ((this._Category != value))
			{
				this.OnCategoryChanging(value);
				this.SendPropertyChanging();
				this._Category = value;
				this.SendPropertyChanged("Category");
				this.OnCategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Int")]
	public System.Nullable<int> GiaBan
	{
		get
		{
			return this._GiaBan;
		}
		set
		{
			if ((this._GiaBan != value))
			{
				this.OnGiaBanChanging(value);
				this.SendPropertyChanging();
				this._GiaBan = value;
				this.SendPropertyChanged("GiaBan");
				this.OnGiaBanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
	public System.Nullable<int> SoLuong
	{
		get
		{
			return this._SoLuong;
		}
		set
		{
			if ((this._SoLuong != value))
			{
				this.OnSoLuongChanging(value);
				this.SendPropertyChanging();
				this._SoLuong = value;
				this.SendPropertyChanged("SoLuong");
				this.OnSoLuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isHot", DbType="Bit")]
	public System.Nullable<bool> isHot
	{
		get
		{
			return this._isHot;
		}
		set
		{
			if ((this._isHot != value))
			{
				this.OnisHotChanging(value);
				this.SendPropertyChanging();
				this._isHot = value;
				this.SendPropertyChanged("isHot");
				this.OnisHotChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorAndSize", DbType="NVarChar(500)")]
	public string ColorAndSize
	{
		get
		{
			return this._ColorAndSize;
		}
		set
		{
			if ((this._ColorAndSize != value))
			{
				this.OnColorAndSizeChanging(value);
				this.SendPropertyChanging();
				this._ColorAndSize = value;
				this.SendPropertyChanged("ColorAndSize");
				this.OnColorAndSizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int")]
	public System.Nullable<int> GiamGia
	{
		get
		{
			return this._GiamGia;
		}
		set
		{
			if ((this._GiamGia != value))
			{
				this.OnGiamGiaChanging(value);
				this.SendPropertyChanging();
				this._GiamGia = value;
				this.SendPropertyChanged("GiamGia");
				this.OnGiamGiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
	public int Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
	public System.DateTime CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MatHang_MatHang", Storage="_MatHangs", ThisKey="ID", OtherKey="ParentID")]
	public EntitySet<MatHang> MatHangs
	{
		get
		{
			return this._MatHangs;
		}
		set
		{
			this._MatHangs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MatHang_MatHang", Storage="_MatHang1", ThisKey="ParentID", OtherKey="ID", IsForeignKey=true)]
	public MatHang MatHang1
	{
		get
		{
			return this._MatHang1.Entity;
		}
		set
		{
			MatHang previousValue = this._MatHang1.Entity;
			if (((previousValue != value) 
						|| (this._MatHang1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._MatHang1.Entity = null;
					previousValue.MatHangs.Remove(this);
				}
				this._MatHang1.Entity = value;
				if ((value != null))
				{
					value.MatHangs.Add(this);
					this._ParentID = value.ID;
				}
				else
				{
					this._ParentID = default(string);
				}
				this.SendPropertyChanged("MatHang1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_MatHangs(MatHang entity)
	{
		this.SendPropertyChanging();
		entity.MatHang1 = this;
	}
	
	private void detach_MatHangs(MatHang entity)
	{
		this.SendPropertyChanging();
		entity.MatHang1 = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Settings")]
public partial class Setting : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _WebName;
	
	private string _Email;
	
	private string _Slider;
	
	private string _KeyWord;
	
	private string _Destination;
	
	private string _AccountEmailSend;
	
	private string _PaySetting;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnWebNameChanging(string value);
    partial void OnWebNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSliderChanging(string value);
    partial void OnSliderChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    partial void OnDestinationChanging(string value);
    partial void OnDestinationChanged();
    partial void OnAccountEmailSendChanging(string value);
    partial void OnAccountEmailSendChanged();
    partial void OnPaySettingChanging(string value);
    partial void OnPaySettingChanged();
    #endregion
	
	public Setting()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string WebName
	{
		get
		{
			return this._WebName;
		}
		set
		{
			if ((this._WebName != value))
			{
				this.OnWebNameChanging(value);
				this.SendPropertyChanging();
				this._WebName = value;
				this.SendPropertyChanged("WebName");
				this.OnWebNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slider", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Slider
	{
		get
		{
			return this._Slider;
		}
		set
		{
			if ((this._Slider != value))
			{
				this.OnSliderChanging(value);
				this.SendPropertyChanging();
				this._Slider = value;
				this.SendPropertyChanged("Slider");
				this.OnSliderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string KeyWord
	{
		get
		{
			return this._KeyWord;
		}
		set
		{
			if ((this._KeyWord != value))
			{
				this.OnKeyWordChanging(value);
				this.SendPropertyChanging();
				this._KeyWord = value;
				this.SendPropertyChanged("KeyWord");
				this.OnKeyWordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Destination", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Destination
	{
		get
		{
			return this._Destination;
		}
		set
		{
			if ((this._Destination != value))
			{
				this.OnDestinationChanging(value);
				this.SendPropertyChanging();
				this._Destination = value;
				this.SendPropertyChanged("Destination");
				this.OnDestinationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountEmailSend", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string AccountEmailSend
	{
		get
		{
			return this._AccountEmailSend;
		}
		set
		{
			if ((this._AccountEmailSend != value))
			{
				this.OnAccountEmailSendChanging(value);
				this.SendPropertyChanging();
				this._AccountEmailSend = value;
				this.SendPropertyChanged("AccountEmailSend");
				this.OnAccountEmailSendChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaySetting", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string PaySetting
	{
		get
		{
			return this._PaySetting;
		}
		set
		{
			if ((this._PaySetting != value))
			{
				this.OnPaySettingChanging(value);
				this.SendPropertyChanging();
				this._PaySetting = value;
				this.SendPropertyChanged("PaySetting");
				this.OnPaySettingChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmailTemplate")]
public partial class tblEmailTemplate : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _EmailContent;
	
	private string _EmailTitle;
	
	private string _EmailTitleGoc;
	
	private string _Des;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEmailContentChanging(string value);
    partial void OnEmailContentChanged();
    partial void OnEmailTitleChanging(string value);
    partial void OnEmailTitleChanged();
    partial void OnEmailTitleGocChanging(string value);
    partial void OnEmailTitleGocChanged();
    partial void OnDesChanging(string value);
    partial void OnDesChanged();
    #endregion
	
	public tblEmailTemplate()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailContent", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string EmailContent
	{
		get
		{
			return this._EmailContent;
		}
		set
		{
			if ((this._EmailContent != value))
			{
				this.OnEmailContentChanging(value);
				this.SendPropertyChanging();
				this._EmailContent = value;
				this.SendPropertyChanged("EmailContent");
				this.OnEmailContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTitle", DbType="NVarChar(MAX)")]
	public string EmailTitle
	{
		get
		{
			return this._EmailTitle;
		}
		set
		{
			if ((this._EmailTitle != value))
			{
				this.OnEmailTitleChanging(value);
				this.SendPropertyChanging();
				this._EmailTitle = value;
				this.SendPropertyChanged("EmailTitle");
				this.OnEmailTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTitleGoc", DbType="NVarChar(MAX)")]
	public string EmailTitleGoc
	{
		get
		{
			return this._EmailTitleGoc;
		}
		set
		{
			if ((this._EmailTitleGoc != value))
			{
				this.OnEmailTitleGocChanging(value);
				this.SendPropertyChanging();
				this._EmailTitleGoc = value;
				this.SendPropertyChanged("EmailTitleGoc");
				this.OnEmailTitleGocChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Des", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Des
	{
		get
		{
			return this._Des;
		}
		set
		{
			if ((this._Des != value))
			{
				this.OnDesChanging(value);
				this.SendPropertyChanging();
				this._Des = value;
				this.SendPropertyChanged("Des");
				this.OnDesChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuc")]
public partial class TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ID;
	
	private int _Type;
	
	private string _TieuDe;
	
	private string _Img;
	
	private string _Des;
	
	private string _Content;
	
	private int _Status;
	
	private System.DateTime _CreateDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    partial void OnDesChanging(string value);
    partial void OnDesChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    #endregion
	
	public TinTuc()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
	public int Type
	{
		get
		{
			return this._Type;
		}
		set
		{
			if ((this._Type != value))
			{
				this.OnTypeChanging(value);
				this.SendPropertyChanging();
				this._Type = value;
				this.SendPropertyChanged("Type");
				this.OnTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string TieuDe
	{
		get
		{
			return this._TieuDe;
		}
		set
		{
			if ((this._TieuDe != value))
			{
				this.OnTieuDeChanging(value);
				this.SendPropertyChanging();
				this._TieuDe = value;
				this.SendPropertyChanged("TieuDe");
				this.OnTieuDeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string Img
	{
		get
		{
			return this._Img;
		}
		set
		{
			if ((this._Img != value))
			{
				this.OnImgChanging(value);
				this.SendPropertyChanging();
				this._Img = value;
				this.SendPropertyChanged("Img");
				this.OnImgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Des", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Des
	{
		get
		{
			return this._Des;
		}
		set
		{
			if ((this._Des != value))
			{
				this.OnDesChanging(value);
				this.SendPropertyChanging();
				this._Des = value;
				this.SendPropertyChanged("Des");
				this.OnDesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this.OnContentChanging(value);
				this.SendPropertyChanging();
				this._Content = value;
				this.SendPropertyChanged("Content");
				this.OnContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
	public int Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
	public System.DateTime CreateDate
	{
		get
		{
			return this._CreateDate;
		}
		set
		{
			if ((this._CreateDate != value))
			{
				this.OnCreateDateChanging(value);
				this.SendPropertyChanging();
				this._CreateDate = value;
				this.SendPropertyChanged("CreateDate");
				this.OnCreateDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
